version: '2'
services:

#Reverse Proxy and LetsEncrypt
  traefik:
    container_name: traefik
    image: traefik:alpine
    restart: always
    networks:
      - srv
    ports:
      - 80:80
      - 443:443
    volumes:
      - /apps/traefik/traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
      - /apps/traefik/acme.json:/acme.json

#Dokuwiki
  wiki:
    container_name: dokuwiki
    image: mprasil/dokuwiki:2018-04-22b
    restart: always
    networks:
      - srv
    ports:
      - "8082:80"
    volumes:
      - /apps/wiki/data/:/dokuwiki/data
      - /apps/wiki/conf/:/dokuwiki/conf
      - /apps/wiki/lib/plugins/:/dokuwiki/lib/plugins
      - /apps/wiki/lib/tpl/:/dokuwiki/lib/tpl
      - /apps/wiki/logs/:/dokuwiki/var/log
    labels:
      - traefik.enable=true
      - "traefik.frontend.rule=Host:doku.YOUR-WEBSITE.com"

networks:
   srv:
