version: '2'
services:

#Dokuwiki
  wiki:
    container_name: dokuwiki
    image: mprasil/dokuwiki:2018-04-22b
    restart: always
    networks:
      - apps
    ports:
      - "8082:80"
    volumes:
      - /doku/wiki/data/:/dokuwiki/data
      - /doku/wiki/conf/:/dokuwiki/conf
      - /doku/wiki/lib/plugins/:/dokuwiki/lib/plugins
      - /doku/wiki/lib/tpl/:/dokuwiki/lib/tpl
      - /doku/wiki/logs/:/dokuwiki/var/log
    labels:
      - traefik.enable=true
      - "traefik.frontend.rule=Host:doku.YOUR-WEBSITE.com"

#Reverse Proxy and LetsEncrypt
  traefik:
    container_name: traefik
    image: traefik:alpine
    restart: always
    networks:
      - apps
    ports:
      - 80:80
      - 443:443
    volumes:
      - /doku/traefik/traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
      - /doku/traefik/acme.json:/acme.json

#NextCloud
  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: always
    networks:
      - apps
    ports:
      - 8081:80
    depends_on:
      - db
    volumes:
      - /doku/nextcloud/:/var/www/html
    labels:
      - traefik.enable=true
      - "traefik.frontend.rule=Host:cloud.YOUR-WEBSITE.com"

  db:
    container_name: nextcloud-db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    networks:
      - apps    
    volumes:
      - /doku/nextclouddb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=CHANGEME
      - MYSQL_PASSWORD=CHANGEME
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

networks:
   apps: